### ISSUE TITLE
Use of kalloc in miniwfa, etc

### ISSUE THREAD

**Issue by lh3** [armintoepfer/aligner-testbed#1]
I saw someone forked miniwfa, so I followed that and came here :-) It is recommended to initialize `km = km_init()` once per thread and then free it with `km_destroy()` close to the end of the thread (should document this). In your code, call `km_init()` before `for(i)` at [this line](https://github.com/armintoepfer/aligner-testbed/blob/e9e44b5ff8a1fae4201fa576d3ca2163ebe3e8ba/src/main.cpp#L154) and free it after the loop. Miniwfa is doing frequent heap allocation and relying on kalloc to reduce the overhead. Without kalloc, it can be ~30% slower. The slowdown may be more noticeable when you align different pairs in multiple threads.

WFA2-lib uses heuristic by default (see smarco/WFA2-lib#7). You need to add `attributes.heuristic.strategy = wf_heuristic_none` if you want to use the exact algorithm. Miniwfa doesn't support any heuristic as I don't have the need for now. It is not hard to implement them.

BTW: 1) I saw you mentioned banding on twitter. I actually like fixed bandwidth. Fixed banding is predictable. We can often get a good sense whether the bandwidth is enough by looking at the cigar or even before getting the alignment. We can then double the bandwidth when we worry it is too small. Such a band doubling heuristic would be at most twice as slow in comparison to optimal banding. Bwa-mem has a version of this. With wavefront reduction, it is hard to tell when the heuristic fails. And when the heuristic fails, we may need more time to do alignment as the score would be higher. 2) ~~I am not sure if WFA works for spliced alignment in its current form. WFA assumes non-exact-match incurs a positive penalty. In spliced alignment, however, intron extension doesn't increase the score.~~ (EDIT: we can make intron extension cost, though I am not sure about the effect of that) I guess there should be a way to make WFA work, but even in that case, WFA may need to fill most part of the DP matrix and lose its key advantage over NW.

**Comment by armintoepfer** [comment]
Hi Heng, welcome to my WFA exploration and thank you for the in-depth analysis :)

I had some serious issues with `kalloc`. Turns out, your approach of duplicating utils for new projects and then changing them, causes issues if I, as an user, wants to combine multiple of your libraries. In this case, it picked up ksw2's kalloc first. This is really a problem and I encourage you to improve this, otherwise I can't use miniwfa and ksw2 out of the box together.

Without heuristics, for my CLR data, both WFA implementations are much slower than running ksw2 with a few banding tricks.

To be honest, it would be incredible to be able to align 2x full-length subreads from the same molecule without any mapping steps, but it has to be faster than the current approach and we need a path for a GPU implementation...it's a challenge. Maybe you have some ideas?

**Comment by lh3** [comment]
`kalloc` is backward compatible. You can replace the kalloc in minimap2 and ksw2 with the one in miniwfa/minigraph.

> Without heuristics, for my CLR data, both WFA implementations are much slower than running ksw2 with a few banding tricks.

Not surprising. WFA shines for near identical long strings but you are probably looking at short strings of ~80% identity in a narrow band. I suspect banding in WFA2-lib may also improve performance, though maybe not much for short dissimilar strings.

> To be honest, it would be incredible to be able to align 2x full-length subreads from the same molecule without any mapping steps

My intuition is that it is hard for WFA+heuristic to beat mapping+alignment for ~10kb strings at 80% identity. I could be wrong without playing with the data.

**Comment by armintoepfer** [comment]
> kalloc is backward compatible

Right but not forward compatible as it looks like. But that's definitely good to know!

> WFA shines for near identical long strings

Even with ksw2 banded? I have to try that soonish.

> My intuition is that it is hard for WFA+heuristic to beat mapping+alignment for ~10kb strings at 80% identity

I agree. 2x 90% is just not good enough for WFA. Good thing that we have a blazing fast ksw2 GPU port 🚀

**Comment by lh3** [comment]
> Even with ksw2 banded? I have to try that soonish.

If you know the exact band width, maybe no, but in practice, it is hard to determine the right band width for complex human SVs in segdups.

Anyway, I am closing this issue as the original issue (use of kalloc) has been resolved.
